### ISSUE TITLE
通过 CSS3 -webkit-tap-highlight-color 去除默认点击高亮

### ISSUE THREAD

**Issue by FishPlusOrange** [FishPlusOrange/pocket-book#13]
在移动端开发过程中，发现一个问题：当点击一个链接时，其就会默认出现灰色高亮。

该样式由属性 [`-webkit-tap-highlight-color`](http://www.css88.com/webkit/-webkit-tap-highlight-color) 控制，可通过设置透明度为0禁用该属性：

```css
* {
    -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
}
```

[Back to TOC](https://github.com/FishPlusOrange/pocket-book/blob/master/README.md)
