### ISSUE TITLE
通过 CSS3 -webkit-appearance 去除输入框默认内阴影

### ISSUE THREAD

**Issue by FishPlusOrange** [FishPlusOrange/pocket-book#14]
在移动端开发过程中，发现一个问题：在 iOS 上，input 和 textarea 默认存在顶部内阴影。

该样式由属性 [`-webkit-appearance`](http://www.css88.com/webkit/-webkit-appearance) 控制，可通过设置值为 none 去除该样式：

```css
input,
textarea {
    -webkit-appearance: none;
}
```

[Back to TOC](https://github.com/FishPlusOrange/pocket-book/blob/master/README.md)
