### ISSUE TITLE
低版本 IE 浏览器下绝对定位的元素未设置背景时无法响应鼠标点击或悬浮事件

### ISSUE THREAD

**Issue by FishPlusOrange** [FishPlusOrange/pocket-book#5]
推荐的解决方案是通过设置 background 属性 hack：

```css
div {
    background: url(about:blank);
}
```

其他解决方案：

- 不使用绝对定位
 
- 添加背景色
 
- 添加透明背景图片

[Back to TOC](https://github.com/FishPlusOrange/pocket-book/edit/master/README.md)
